name: Terraform S3

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform_operation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Action
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            # Attempt to import first in case it was created in a previous session
            terraform import aws_s3_bucket.jvai_cdn_bucket jvai-cdn-bucket-unique || true
            terraform apply -auto-approve
          else
            # Link the bucket to the state before trying to destroy
            terraform import aws_s3_bucket.jvai_cdn_bucket jvai-cdn-bucket-unique || true
            terraform destroy -auto-approve
          fi